name: Deploy Laravel Docker on Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Stop old containers
        run: docker compose -f C:\xampp\htdocs\docker-laravel\docker-compose.yml down

      - name: Build & Run containers
        run: docker compose -f C:\xampp\htdocs\docker-laravel\docker-compose.yml up -d --build

      - name: Run Laravel commands
        run: |
          docker exec laravel_app php artisan key:generate
          docker exec laravel_app php artisan migrate --force
          docker exec laravel_app php artisan optimize:clear
          docker exec -d laravel_app php artisan serve --host=0.0.0.0 --port=8000
